### ISSUE TITLE
Game Install location

### ISSUE THREAD

**Issue by MattA-Official** [NALStudio/NALStudio-Game-Launcher#1]
When you install a game, you should be asked where you want to install it with the defaults filled in. I don't think this needs a long description as it is self-explanatory.

**Comment by NALStudio** [comment]
Too hard to implement currently. Would require UAC permissions and other stuff...

**Comment by NALStudio** [comment]
Bruh, now it works

**Comment by NALStudio** [comment]
Still broken, but at least it works... I guess...
